# # Preload the image first
# preload = /home/milan/.config/hypr/wallpapers/hyperspace-5120x2880-26285.jpg
# preload = /home/milan/.config/hypr/wallpapers/astronaut-3840x2400-2460.jpg
# preload = /home/milan/.config/hypr/wallpapers/mercedes-amg-sl-63-4matic-5120x3461-10828.jpg
preload = /home/milan/.config/hypr/wallpapers/tyler-lastovich-ddLiNMqWAOM-unsplash.jpg
#
# # Set the wallpaper for your monitor
# # wallpaper = eDP-1,/home/milan/.config/hypr/wallpapers/hyperspace-5120x2880-26285.jpg
#
wallpaper {
    monitor = eDP-1
    path = /home/milan/.config/hypr/wallpapers/tyler-lastovich-ddLiNMqWAOM-unsplash.jpg
    timeout = 1000
    fit_mode = cover
}

