#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar/"
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=36        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="JetBrainsMono Nerd Font Mono:Bold:17.0"  \
                     icon.color=$WHITE                 \
                     label.font="JetBrainsMono Nerd Font Mono:Bold:14.0" \
                     label.color=$WHITE                \
					 background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.


#Left side
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/front_app.sh"


# export EMPTY_WORKSPACES
# export FOCUSED_WORKSPACE
# source "$ITEM_DIR/space.sh"


# source "$ITEM_DIR/media.sh"
source "$ITEM_DIR/media_title.sh"
source "$ITEM_DIR/media_artist.sh"

# Right side
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
