#!/bin/bash

# set the colors
source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# update borders
borders active_color=$ACCENT_COLOR inactive_color=0xff494d64 width=6.0 &

sketchybar --bar position=top height=37 blur_radius=0 color=0x1a363537 display=all

source "$CONFIG_DIR/items/default.sh"

# Right Side Items
source "$CONFIG_DIR/items/time.sh"

source "$CONFIG_DIR/items/battery.sh"

source "$CONFIG_DIR/items/cpu.sh"

source "$CONFIG_DIR/items/ssd.sh"

# Left Side Items
source "$CONFIG_DIR/items/apple.sh"

source "$CONFIG_DIR/items/spaces2.sh"

source "$CONFIG_DIR/items/front_app.sh"

# Left and right side notch
source "$CONFIG_DIR/items/music.sh"

sketchybar --update
